In [2]:
import numpy as np

In [3]:
arr = np.arange(25).reshape(5,5)

In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
arr **2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

In [6]:
arr+=1

In [7]:
arr+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [8]:
arr-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
arr**3

array([[    1,     8,    27,    64,   125],
       [  216,   343,   512,   729,  1000],
       [ 1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000],
       [ 9261, 10648, 12167, 13824, 15625]], dtype=int32)

In [10]:
n=10

In [20]:
for i in range(n):
    for j in range(n):
        if i==j or j==n-1-i:print("*",end="")
        else:print(" ",end="")
    print()

*        *
 *      * 
  *    *  
   *  *   
    **    
    **    
   *  *   
  *    *  
 *      * 
*        *


In [21]:
n=10 
for i in range(n):
    for j in range(n):
        if i==j or j==n-1-i:print("*",end="")
        else:print(" ",end="")
    print()

*        *
 *      * 
  *    *  
   *  *   
    **    
    **    
   *  *   
  *    *  
 *      * 
*        *
